unifly-aero/powergrid

web/datasources/groupingdatasource.js, web/powergrid.js
- Allow html content in group projection
- Allow to specify hidden columns
=> AIR-468 Change UAS screen

web/powergrid.js
fix autosizing of last visible column if any columns come after that have been hidden
=> Fix autosizing of last visible column

web/powergrid.js
if removed rows affected viewport begin
=> fix bug with viewport recalculation

web/extensions/export_csv.js
Not related to the cause of AIR-4034
=> Fix boolean export in csv

web/datasources/asynctreegriddatasource.js, web/datasources/bufferedasynctreesource.js, web/datasources/csvdatasource.js, web/datasources/groupingdatasource.js, web/datasources/synctreegriddatasource.js, web/datasources/treesource.js, web/demos/airports.html, web/demos/export.html, web/extensions/export_csv.js
=> add queryForExport to TreeSource and DataSource

web/extensions/filtering_option.js
=> option filtering now supports searching in arrays

web/extensions/columnsizing.js
Add minimum column size to prevent from accidentally irreparably shrink a column down to nothing. 
=> add minimum column size

web/datasources/summarizingdatasource.js
=> export to csv fails with summary ds

web/extensions/filtering.js, web/extensions/filtering_option.js, web/extensions/filtering_scalar.js, web/powergrid.js, web/templates/filterPane.js, web/translations.js
- [V] the changes in this pull request should not break backward compatibility; if 
- [V] the code changes are generic and do not contain any application-specific code.
- [V] if the code changes include new dependencies, my motivation for doing so is
=> AIR-4856 translations

web/powergrid.js
=> AIR-4856 fix es

web/extensions/export_csv.js
- [v] the changes in this pull request should not break backward compatibility; if 
- [v] the code changes are generic and do not contain any application-specific code.
- [v] if the code changes include new dependencies, my motivation for doing so is
=> AIR-5042 Use formatters when exporting CSV's

web/extensions/filtering_scalar.js, web/extensions/grouping.js, web/templates/grouper.js, web/translations.js
- [v] the changes in this pull request should not break backward compatibility; if 
- [v] the code changes are generic and do not contain any application-specific code.
- [v] if the code changes include new dependencies, my motivation for doing so is
=> AIR-5042 Fix filter translation

web/extensions/export_csv.js
=> Add parameter to disable export of column

web/extensions/subview.js
=> AIR-5282 : Exception when you delete a record with a subview open.

web/extensions/filtering.js, web/extensions/filtering_option.js
=> Default filter options

web/extensions/filtering.js
AIR-6655
- [x ] the changes in this pull request should not break backward compatibility; if 
- [x ] the code changes are generic and do not contain any application-specific code.
- [x ] if the code changes include new dependencies, my motivation for doing so is
=> Default filter options fix

web/translations.js
=> Translation powergrid - drag columns here to group

web/extensions/dragging.js, web/extensions/filtering.js, web/extensions/grouping.js, web/main.d.ts, web/main.js, web/powergrid.js
=> grouping and filtering enhancements

package.json, web/main.d.ts
=> more typings

web/extensions/dragging.js
=> fix reordering of columns

web/powergrid.js, web/tests/filtering.js, web/tests/pluginloadorder.js, web/tests/utils.js, web/utils.js
=> debounce viewport updating instead of simply rate limiting

web/extensions/dragging.js, web/main.d.ts, web/powergrid.js
=> column hiding and fixed columns

web/extensions/eventhandlers.js, web/main.d.ts
=> add api for basic event handling

web/main.d.ts, web/powergrid.css
=> Fix grouprow clicks

web/extensions/grouping.js
=> fix rendering issue with external groupers and newer jQuery versions

web/datasources/bufferedasynctreesource.js
=> Fix fetchEnd bein equal to fetchStart causing rows not loading

web/powergrid.js
=> fix race condition while filtering

web/extensions/columnmoving.js, web/extensions/dragging.js
=> UP-1494. Dont call adjustColumnPositions unnecessarily (has very slow performance in Safari)

package-lock.json, package.json
=> pin jsrender version

web/main.d.ts
=> Min and max can also be null

web/main.d.ts, web/powergrid.js
=> save settings through settingsProvider grid option

web/datasources/asynctreegriddatasource.js
=> Merge master

web/main.d.ts
=> expose updateColumns()
